// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

/**
 * Props for ProcessMetricsFunction
 */
export interface ProcessMetricsFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambda/process-metrics.
 */
export class ProcessMetricsFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ProcessMetricsFunctionProps) {
    super(scope, id, {
      description: 'src/lambda/process-metrics.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/lambda/process-metrics.lambda')),
    });
  }
}